# Generated by Django 2.2.12 on 2020-04-03 12:34

import api.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receitas', djongo.models.fields.ArrayField(model_container=api.models.Receita)),
            ],
        ),
    ]
